// Generated by qa-audit-agent from https://quotes.toscrape.com/
// Run with: BASE_URL=https://quotes.toscrape.com npx playwright test
// Needs: @playwright/test and @axe-core/playwright
const { test, expect } = require('@playwright/test');
const { AxeBuilder } = require('@axe-core/playwright');

const BASE_URL = (process.env.BASE_URL || "https://quotes.toscrape.com").replace(/\/$/, '');
const at = (path) => BASE_URL + path;

function actualType(value) {
  if (value === null) return 'null';
  if (Array.isArray(value)) return 'array';
  if (Number.isInteger(value)) return 'integer';
  return typeof value;
}
function conforms(shape, value, path = '$') {
  if (!shape) return [];
  const actual = actualType(value);
  if (shape.type === 'number' ? !['number', 'integer'].includes(actual) : actual !== shape.type) {
    return [`${path}: expected ${shape.type}, got ${actual}`];
  }
  if (shape.type === 'array') {
    return value.slice(0, 3).flatMap((item, i) => conforms(shape.item, item, `${path}[${i}]`));
  }
  if (shape.type === 'object') {
    return Object.entries(shape.keys || {}).flatMap(([key, sub]) =>
      key in value ? conforms(sub, value[key], `${path}.${key}`) : [`${path}.${key}: missing`],
    );
  }
  return [];
}

test.describe("page", () => {
  test("Page loads without errors: /", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /", async ({ page, request }) => {
    await page.goto(at("/"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /login", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/login"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /login", async ({ page, request }) => {
    await page.goto(at("/login"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /author/Albert-Einstein", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/author/Albert-Einstein"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /author/Albert-Einstein", async ({ page, request }) => {
    await page.goto(at("/author/Albert-Einstein"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /tag/change/page/1/", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/tag/change/page/1/"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /tag/change/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/change/page/1/"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /tag/deep-thoughts/page/1/", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/tag/deep-thoughts/page/1/"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /tag/deep-thoughts/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/deep-thoughts/page/1/"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /tag/thinking/page/1/", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/tag/thinking/page/1/"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /tag/thinking/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/thinking/page/1/"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /tag/world/page/1/", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/tag/world/page/1/"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /tag/world/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/world/page/1/"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /author/J-K-Rowling", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/author/J-K-Rowling"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /author/J-K-Rowling", async ({ page, request }) => {
    await page.goto(at("/author/J-K-Rowling"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /tag/abilities/page/1/", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/tag/abilities/page/1/"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /tag/abilities/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/abilities/page/1/"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /tag/choices/page/1/", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/tag/choices/page/1/"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /tag/choices/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/choices/page/1/"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /tag/inspirational/page/1/", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/tag/inspirational/page/1/"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /tag/inspirational/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/inspirational/page/1/"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });

  test("Page loads without errors: /tag/life/page/1/", async ({ page, request }) => {
    const errors = [];
    const bad = [];
    page.on('console', (m) => m.type() === 'error' && !m.text().startsWith('Failed to load resource') && errors.push(m.text()));
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && bad.push(r.status() + ' ' + r.url()));
    const response = await page.goto(at("/tag/life/page/1/"));
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    expect(response.status()).toBeLessThan(400);
    expect((await page.title()).trim()).not.toBe('');
    expect(errors).toEqual([]);
    expect(bad).toEqual([]);
  });

  test("Page structure (one h1, lang, viewport): /tag/life/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/life/page/1/"));
    expect(await page.locator('h1').count()).toBe(1);
    expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
    expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);
  });
});

test.describe("a11y", () => {
  test("No serious accessibility violations: /", async ({ page, request }) => {
    await page.goto(at("/"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /login", async ({ page, request }) => {
    await page.goto(at("/login"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /author/Albert-Einstein", async ({ page, request }) => {
    await page.goto(at("/author/Albert-Einstein"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /tag/change/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/change/page/1/"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /tag/deep-thoughts/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/deep-thoughts/page/1/"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /tag/thinking/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/thinking/page/1/"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /tag/world/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/world/page/1/"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /author/J-K-Rowling", async ({ page, request }) => {
    await page.goto(at("/author/J-K-Rowling"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /tag/abilities/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/abilities/page/1/"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /tag/choices/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/choices/page/1/"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /tag/inspirational/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/inspirational/page/1/"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });

  test("No serious accessibility violations: /tag/life/page/1/", async ({ page, request }) => {
    await page.goto(at("/tag/life/page/1/"));
    const { violations } = await new AxeBuilder({ page }).analyze();
    expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);
  });
});

test.describe("navigation", () => {
  test("Navigation: \"Next →\" leads to /page/2/", async ({ page, request }) => {
    await page.goto(at("/"));
    await page.locator('a[href=' + "\"/page/2/\"" + ']').first().click();
    const trim = (p) => (p.length > 1 ? p.replace(/\/$/, '') : p);
    await page.waitForURL((url) => trim(url.pathname + url.search) === "/page/2");
  });
});

test.describe("links", () => {
  test("Link works: /tag/live/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/live/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/miracle/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/miracle/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/miracles/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/miracles/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /author/Jane-Austen (from /)", async ({ page, request }) => {
    const res = await request.get(at("/author/Jane-Austen"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/aliteracy/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/aliteracy/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/books/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/books/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/classic/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/classic/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/humor/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/humor/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /author/Marilyn-Monroe (from /)", async ({ page, request }) => {
    const res = await request.get(at("/author/Marilyn-Monroe"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/be-yourself/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/be-yourself/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/adulthood/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/adulthood/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/success/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/success/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/value/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/value/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /author/Andre-Gide (from /)", async ({ page, request }) => {
    const res = await request.get(at("/author/Andre-Gide"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/love/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/love/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /author/Thomas-A-Edison (from /)", async ({ page, request }) => {
    const res = await request.get(at("/author/Thomas-A-Edison"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/edison/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/edison/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/failure/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/failure/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/paraphrased/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/paraphrased/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /author/Eleanor-Roosevelt (from /)", async ({ page, request }) => {
    const res = await request.get(at("/author/Eleanor-Roosevelt"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/misattributed-eleanor-roosevelt/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/misattributed-eleanor-roosevelt/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /author/Steve-Martin (from /)", async ({ page, request }) => {
    const res = await request.get(at("/author/Steve-Martin"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/obvious/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/obvious/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/simile/page/1/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/simile/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /page/2/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/page/2/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/love/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/love/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/inspirational/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/inspirational/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/life/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/life/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/humor/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/humor/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/books/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/books/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/reading/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/reading/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/friendship/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/friendship/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/friends/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/friends/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/truth/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/truth/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/simile/ (from /)", async ({ page, request }) => {
    const res = await request.get(at("/tag/simile/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /author/Terry-Pratchett (from /tag/thinking/page/1/)", async ({ page, request }) => {
    const res = await request.get(at("/author/Terry-Pratchett"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/open-mind/page/1/ (from /tag/thinking/page/1/)", async ({ page, request }) => {
    const res = await request.get(at("/tag/open-mind/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/friends/page/1/ (from /tag/inspirational/page/1/)", async ({ page, request }) => {
    const res = await request.get(at("/tag/friends/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/heartbreak/page/1/ (from /tag/inspirational/page/1/)", async ({ page, request }) => {
    const res = await request.get(at("/tag/heartbreak/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("Link works: /tag/sisters/page/1/ (from /tag/inspirational/page/1/)", async ({ page, request }) => {
    const res = await request.get(at("/tag/sisters/page/1/"), { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("External link works: www.goodreads.com/quotes", async ({ page, request }) => {
    const res = await request.get("https://www.goodreads.com/quotes", { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });

  test("External link works: www.zyte.com/", async ({ page, request }) => {
    const res = await request.get("https://www.zyte.com/", { maxRedirects: 5 });
    test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
    expect(res.status()).toBeLessThan(400);
  });
});

test.describe("forms", () => {
  test("Form /login on /login: valid data passes validation (not submitted)", async ({ page, request }) => {
    await page.goto(at("/login"));
    const form = page.locator('form').nth(0);
    await form.locator("#username").first().fill("Test value");
    await form.locator("#password").first().fill("Passw0rd!xyz");
    expect(await form.evaluate((f) => [...f.elements].filter((el) => el.willValidate && !el.validity.valid).map((el) => el.name || el.id))).toEqual([]);
  });
});
