const fs = require('node:fs');
const { pathOf } = require('./generate');

// The exported spec embeds the checker verbatim. It is read from the file on disk, not from
// Function.toString(), because test coverage instrumentation rewrites functions in memory.
function shapeHelpers() {
  const source = fs.readFileSync(require.resolve('./shape'), 'utf8');
  const start = source.indexOf('// embed-start');
  const end = source.indexOf('// embed-end');
  return source.slice(source.indexOf('\n', start) + 1, end).trim();
}

const q = (value) => JSON.stringify(value);

function target(url, origin) {
  return new URL(url).origin === origin ? `at(${q(pathOf(url))})` : q(url);
}

function body(c, origin) {
  const go = (url) => `await page.goto(${target(url, origin)});`;
  const form = `page.locator('form').nth(${c.formIndex})`;
  switch (c.type) {
    case 'page-loads':
      return `  const errors = [];
  const bad = [];
  page.on('console', (m) => {
    if (m.type() !== 'error' || m.text().startsWith('Failed to load resource')) return;
    if (own(m.location().url) || /content security policy/i.test(m.text())) errors.push(m.text());
  });
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('response', (r) => r.status() >= 400 && r.request().resourceType() !== 'document' && own(r.url()) && bad.push(r.status() + ' ' + r.url()));
  const response = await page.goto(${target(c.url, origin)});
  await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
  expect(response.status()).toBeLessThan(400);
  expect((await page.title()).trim()).not.toBe('');
  expect(errors).toEqual([]);
  expect(bad).toEqual([]);`;
    case 'page-structure':
      return `  ${go(c.url)}
  expect(await page.locator('h1').count()).toBe(1);
  expect(await page.evaluate(() => document.documentElement.lang)).not.toBe('');
  expect(await page.locator('meta[name="viewport"]').count()).toBeGreaterThan(0);`;
    case 'page-a11y':
      return `  ${go(c.url)}
  const { violations } = await new AxeBuilder({ page }).analyze();
  expect(violations.filter((v) => ['serious', 'critical'].includes(v.impact)).map((v) => v.id)).toEqual([]);`;
    case 'link-ok':
      return `  const res = await request.get(${target(c.url, origin)}, { maxRedirects: 5 });
  test.skip([401, 403, 429, 999].includes(res.status()), 'cannot be verified automatically');
  expect(res.status()).toBeLessThan(400);`;
    case 'nav-click':
      return `  ${go(c.url)}
  await page.locator('a[href=' + ${q(JSON.stringify(c.raw))} + ']').first().click();
  const trim = (p) => (p.length > 1 ? p.replace(/\\/$/, '') : p);
  await page.waitForURL((url) => trim(url.pathname + url.search) === ${q(c.expectedPath.replace(/(.)\/$/, '$1'))});`;
    case 'form-required':
      return `  ${go(c.url)}
  const form = ${form};
  expect(await form.evaluate((f) => f.checkValidity())).toBe(false);
${c.fields.map((f) => `  expect(await form.locator(${q(f.selector)}).first().evaluate((el) => el.validity.valueMissing)).toBe(true);`).join('\n')}`;
    case 'form-validation':
      return `  ${go(c.url)}
  const field = ${form}.locator(${q(c.selector)}).first();
  await field.fill(${q(c.bad)});
  expect(await field.evaluate((el) => el.validity.${c.flag})).toBe(true);
  await field.fill(${q(c.good)});
  expect(await field.evaluate((el) => el.validity.valid)).toBe(true);`;
    case 'form-accepts-valid':
      return `  ${go(c.url)}
  const form = ${form};
${c.values
  .map(({ selector, tag, type, value }) => {
    const field = `form.locator(${q(selector)}).first()`;
    if (type === 'checkbox' || type === 'radio') return `  await ${field}.check();`;
    if (tag === 'select') return `  await ${field}.selectOption(${q(value)});`;
    return `  await ${field}.fill(${q(value)});`;
  })
  .join('\n')}
  expect(await form.evaluate((f) => [...f.elements].filter((el) => el.willValidate && !el.validity.valid).map((el) => el.name || el.id))).toEqual([]);`;
    case 'api-contract':
      return `  const started = Date.now();
  const res = await request.get(${target(c.url, origin)});
  expect(res.status()).toBeLessThan(400);
  expect(conforms(${JSON.stringify(c.shape)}, await res.json())).toEqual([]);
  expect(Date.now() - started).toBeLessThan(3000);`;
    default:
      return null;
  }
}

function exportPlaywrightSpec(cases, model) {
  const groups = {};
  for (const c of cases) {
    const code = body(c, model.origin);
    if (code) (groups[c.group] ||= []).push(`  test(${q(c.name)}, async ({ page, request }) => {\n${code.replace(/^/gm, '  ')}\n  });`);
  }
  const describes = Object.entries(groups).map(([group, tests]) => `test.describe(${q(group)}, () => {\n${tests.join('\n\n')}\n});`);

  return `// Generated by qa-audit-agent from ${model.startUrl}
// Run with: BASE_URL=${model.origin} npx playwright test
// Needs: @playwright/test and @axe-core/playwright
const { test, expect } = require('@playwright/test');
const { AxeBuilder } = require('@axe-core/playwright');

const BASE_URL = (process.env.BASE_URL || ${q(model.origin)}).replace(/\\/$/, '');
const at = (path) => BASE_URL + path;
// Problems caused by third-party scripts (analytics, captchas) are not the site's own.
const own = (url) => {
  try {
    return new URL(url).origin === new URL(BASE_URL).origin;
  } catch {
    return true;
  }
};

${shapeHelpers()}

${describes.join('\n\n')}
`;
}

module.exports = { exportPlaywrightSpec };
